import { Direction } from "../helpers"

const cc2Tiles = [
	[["unknown", 0, ""]],
	[],
	[["wall", 0, ""]],
	[["ice", 0, ""]],
	[["iceCorner", 2, ""]],
	[["iceCorner", 3, ""]],
	[["iceCorner", 0, ""]],
	[["iceCorner", 1, ""]],
	[["water", 0, ""]],
	[["fire", 0, ""]],
	[["forceFloor", 0, ""]],
	[["forceFloor", 1, ""]],
	[["forceFloor", 2, ""]],
	[["forceFloor", 3, ""]],
	[["toggleWall", 0, "true"]],
	[["toggleWall", 0, "false"]],
	[["teleportRed", 0, ""]],
	[["teleportBlue", 0, ""]],
	[["teleportYellow", 0, ""]],
	[["teleportGreen", 0, ""]],
	[["exit", 0, ""]],
	[["slime", 0, ""]],
	[["chip", null, ""], null],
	[["dirtBlock", null, ""], null],
	[["walker", null, ""], null],
	[["glider", null, ""], null],
	[["iceBlock", null, ""], null],
	[["thinWall", 1, ""], null],
	[["thinWall", 2, ""], null],
	[["thinWall", 1, ""], ["thinWall", 2, ""], null],
	[["gravel", 0, ""]],
	[["buttonGreen", 0, ""]],
	[["buttonBlue", 0, ""]],
	[["tankBlue", null, ""], null],
	[["doorRed", 0, ""]],
	[["doorBlue", 0, ""]],
	[["doorYellow", 0, ""]],
	[["doorGreen", 0, ""]],
	[["keyRed", 0, ""], null],
	[["keyBlue", 0, ""], null],
	[["keyYellow", 0, ""], null],
	[["keyGreen", 0, ""], null],
	[["echip", 0, ""], null],
	[["echipPlus", 0, ""], null],
	[["echipGate", 0, ""]],
	[["popupWall", 0, ""]],
	[["appearingFair", 0, ""]],
	[["invisibleWall", 0, ""]],
	[["blueWall", 0, "real"]],
	[["blueWall", 0, "fake"]],
	[["dirt", 0, ""]],
	[["ant", null, ""], null],
	[["centipede", null, ""], null],
	[["ball", null, ""], null],
	[["blob", null, ""], null],
	[["teethRed", null, ""], null],
	[["fireball", null, ""], null],
	[["buttonRed", 0, ""]],
	[["buttonBrown", 0, ""]],
	[["bootIce", 0, ""], null],
	[["bootForceFloor", 0, ""], null],
	[["bootFire", 0, ""], null],
	[["bootWater", 0, ""], null],
	[["thiefKey", 0, ""]],
	[["bomb", 0, ""], null],
	[["trap", 0, ""]],
	[["trap", 0, ""]],
	[["cloneMachine", 0, "cc1"]],
	[["cloneMachine", 0, ""]],
	[["hint", 0, ""]],
	[["forceFloor", 0, "random"]],
	[["buttonGray", 0, ""]],
	[["swivel", 2, ""]],
	[["swivel", 3, ""]],
	[["swivel", 0, ""]],
	[["swivel", 1, ""]],
	[["timeBonus", 0, ""], null],
	[["stopwatch", 0, ""], null],
	[["transmogrifier", 0, ""]],
	[["railroadTrack", 0, ""]], // Oh no
	[["steelWall", 0, ""]],
	[["tnt", 0, ""], null],
	[["helmet", 0, ""], null],
	[["unknown", 0, ""]],
	[["unknown", 0, ""]],
	[["unknown", 0, ""]],
	[["melinda", null, ""], null],
	[["teethBlue", null, ""], null],
	[["unknown", 0, ""]],
	[["bootDirt", 0, ""], null],
	[["signMale", 0, ""]],
	[["signFemale", 0, ""]],
	[["notGate", 0, ""]], // Custom stuff
	[["unknown", 0, ""]],
	[["buttonPurple", 0, ""]],
	[["flameJet", 0, "off"]],
	[["flameJet", 0, "on"]],
	[["buttonOrange", 0, ""]],
	[["lightningBolt", 0, ""], null],
	[["tankYellow", null, ""], null],
	[["complexButtonYellow", 0, ""]],
	[["mirrorChip", null, ""], null],
	[["mirrorMelinda", null, ""], null],
	[["unknown", 0, ""]],
	[["bowlingBall", 0, ""], null],
	[["rover", null, ""], null],
	[["timeBonus", 0, "minus"], null],
	[["customFloor", 0, null]],
	[["unknown", 0, ""]],
	[["thinWall", 0, null], null],
	[["unknown", 0, ""]],
	[["railroadSign", 0, ""], null],
	[["customWall", 0, null]],
	[["letterTile", 0, null]],
	[["outlineContinuos", 0, "on"]],
	[["outlineContinuos", 0, "off"]],
	[["unknown", 0, ""]],
	[["unknown", 0, ""]],
	[["modifier8", 0, null]],
	[["modifier16", 0, null]],
	[["modifier32", 0, null]],
	[["unknown", 0, ""]],
	[["bonus", 0, "10"], null],
	[["bonus", 0, "100"], null],
	[["bonus", 0, "1000"], null],
	[["wallGreen", 0, ""]],
	[["wallGreen", 0, "fake"]],
	[["noSign", 0, ""], null],
	[["bonus", 0, "*2"], null],
	[["directionalBlock", null, null], null],
	[["floorMimic", null, ""], null],
	[["greenBomb", 0, ""], null],
	[["greenChip", 0, ""], null],
	[["unknown", 0, ""]],
	[["unknown", 0, ""]],
	[["buttonBlack", 0, ""]],
	[["toggleSwitch", 0, "off"]],
	[["toggleSwitch", 0, "on"]],
	[["thiefTool", 0, ""]],
	[["ghost", null, ""], null],
	[["foil", 0, ""], null],
	[["turtle", 0, ""]],
	[["eye", 0, ""], null],
	[["bribe", 0, ""], null],
	[["bootSpeed", 0, ""], null],
	[["unknown", 0, ""]],
	[["hook", 0, ""], null],
] as const

export type cc2TileNames =
	| Exclude<typeof cc2Tiles[number][0], undefined>[0]
	// Indirect tile additions
	| "canopy"
	| "wire"
	| "wireTunnel"
	| "andGate"
	| "orGate"
	| "xorGate"
	| "latchGate"
	| "countGate"
	| "nandGate"
	| "latchGateMirror"
export type cc2Tile = [cc2TileNames, Direction, string?]

export default (cc2Tiles as unknown) as cc2Tile[][]
