import { Direction } from "../helpers"
const data: [string, Direction?, string?][][] = [
	[],
	[["wall"]],
	[["echip"]],
	[["water"]],
	[["fire"]],
	[["invisibleWall"]],
	[["thinWall", 0]],
	[["thinWall", 3]],
	[["thinWall", 2]],
	[["thinWall", 1]],
	[["dirtBlock"]],
	[["dirt"]],
	[["ice"]],
	[["forceFloor", 2]],
	[["dirtBlock", 0]],
	[["dirtBlock", 3]],
	[["dirtBlock", 2]],
	[["dirtBlock", 1]],
	[["forceFloor", 0]],
	[["forceFloor", 1]],
	[["forceFloor", 3]],
	[["exit"]],
	[["doorBlue"]],
	[["doorRed"]],
	[["doorGreen"]],
	[["doorYellow"]],
	[["iceCorner", 3]],
	[["iceCorner", 0]],
	[["iceCorner", 1]],
	[["iceCorner", 2]],
	[["blueWall", 0, "real"]],
	[["blueWall", 0, "fake"]],
	[["wall"]],
	[["thiefTool"]],
	[["echipGate"]],
	[["buttonGreen"]],
	[["buttonRed"]],
	[["toggleWall", 0, "on"]],
	[["toggleWall", 0, "off"]],
	[["buttonBrown"]],
	[["buttonBlue"]],
	[["teleportBlue"]],
	[["bomb"]],
	[["trap"]],
	[["appearingWall"]],
	[["gravel"]],
	[["popupWall"]],
	[["hint"]],
	[
		["thinWall", 1],
		["thinWall", 2],
	],
	[["cloneMachine", 0, "cc1"]],
	[["forceFloorRandom"]],
	// The great wall of internal tiles
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["iceBlock"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	[["wall"]],
	...([
		"ant",
		"fireball",
		"ball",
		"tankBlue",
		"glider",
		"teethRed",
		"walker",
		"blob",
		"centipede",
	]
		.map(val => [[[val, 0]], [[val, 3]], [[val, 2]], [[val, 1]]]) // Flat map, basically
		.reduce((acc, val) => [...acc, ...val], []) as [string, Direction][][]),
	[["keyBlue"]],
	[["keyRed"]],
	[["keyGreen"]],
	[["keyYellow"]],
	[["bootWater"]],
	[["bootFire"]],
	[["bootIce"]],
	[["bootForceFloor"]],
	[["chip", 0]],
	[["chip", 3]],
	[["chip", 2]],
	[["chip", 1]],
]

export default data
