#include <stdio.h>
#define NANOPRINTF_IMPLEMENTATION
#define NANOPRINTF_VISIBILITY_STATIC
#define NANOPRINTF_USE_FIELD_WIDTH_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_PRECISION_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_FLOAT_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_LARGE_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_BINARY_FORMAT_SPECIFIERS 0
#define NANOPRINTF_USE_WRITEBACK_FORMAT_SPECIFIERS 0
#include "./printf.h"

// Copied from EMMALLOC_ALIAS
#define PRINTF_ALIAS(ALIAS, ORIGINAL) \
  extern __typeof(ORIGINAL) ALIAS __attribute__((weak, alias(#ORIGINAL)));

PRINTF_ALIAS(snprintf, npf_snprintf);
PRINTF_ALIAS(vsnprintf, npf_vsnprintf);
